version: "2"

services:
  
  flask-api:
    restart: always
    image: flask-couch-microservice
    build: .
    environment:
      - MODE=dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pass
      - DB_URL='http://localhost:5984/'
    volumes:
      - .:/code 
    ports:
      - "2020:2020"