version: "2"

services:
  
  flask-api:
    restart: always
    image: flask-couch-microservice
    build: .
    environment:
      - MODE=dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pass
      #- DB_URL='http://54.68.14.217:5000/people'
    volumes:
      - .:/code 
    ports:
      - "5000:5000"