version: "2"

services:
  
  flask-api:
    restart: always
    image: flask-couch-microservice
    build: .
    environment:
      - MODE=dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pass
      - DB_URL='http://'ADMIN_USERNAME+':'+ADMIN_PASSWORD+'@54.68.14.217:5984/'
    volumes:
      - .:/code 
    ports:
      - "5000:5000"